-- MySQL Script generated by MySQL Workbench
-- 06/25/17 20:30:55
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema seaandbeach
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `seaandbeach` ;

-- -----------------------------------------------------
-- Schema seaandbeach
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `seaandbeach` DEFAULT CHARACTER SET utf8 ;
USE `seaandbeach` ;

-- -----------------------------------------------------
-- Table `seaandbeach`.`apartamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `seaandbeach`.`apartamento` ;

CREATE TABLE IF NOT EXISTS `seaandbeach`.`apartamento` (
  `Apartamento` INT(11) NOT NULL,
  `Apto` INT(11) NOT NULL,
  PRIMARY KEY (`Apartamento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `Apartamento_UNIQUE` ON `seaandbeach`.`apartamento` (`Apartamento` ASC);


-- -----------------------------------------------------
-- Table `seaandbeach`.`categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `seaandbeach`.`categoria` ;

CREATE TABLE IF NOT EXISTS `seaandbeach`.`categoria` (
  `idCategoria` INT(11) NOT NULL AUTO_INCREMENT,
  `TipoCategoria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `idMenu_UNIQUE` ON `seaandbeach`.`categoria` (`idCategoria` ASC);


-- -----------------------------------------------------
-- Table `seaandbeach`.`categoriaitem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `seaandbeach`.`categoriaitem` ;

CREATE TABLE IF NOT EXISTS `seaandbeach`.`categoriaitem` (
  `idCategoriaItem` INT(11) NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Foto` VARCHAR(45) NOT NULL,
  `idCategoria` INT(11) NOT NULL,
  PRIMARY KEY (`idCategoriaItem`),
  CONSTRAINT `fk_CategoriaItem_Categoria1`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `seaandbeach`.`categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 22
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `idCategoriaItem_UNIQUE` ON `seaandbeach`.`categoriaitem` (`idCategoriaItem` ASC);

CREATE INDEX `fk_CategoriaItem_Categoria1_idx` ON `seaandbeach`.`categoriaitem` (`idCategoria` ASC);


-- -----------------------------------------------------
-- Table `seaandbeach`.`modocierredecaja`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `seaandbeach`.`modocierredecaja` ;

CREATE TABLE IF NOT EXISTS `seaandbeach`.`modocierredecaja` (
  `idModoCierreDeCaja` INT(3) UNSIGNED NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idModoCierreDeCaja`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `seaandbeach`.`cierredecaja`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `seaandbeach`.`cierredecaja` ;

CREATE TABLE IF NOT EXISTS `seaandbeach`.`cierredecaja` (
  `idCierreDeCaja` INT(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  `NumCierreDeCaja` VARCHAR(45) NOT NULL,
  `Fecha` DATE NOT NULL,
  `Hora` TIME NOT NULL,
  `Cedula` INT(12) NOT NULL,
  `idModoCierreDeCaja` INT(3) UNSIGNED NOT NULL,
  PRIMARY KEY (`idCierreDeCaja`),
  CONSTRAINT `fk_cierredecaja_modocierredecaja1`
    FOREIGN KEY (`idModoCierreDeCaja`)
    REFERENCES `seaandbeach`.`modocierredecaja` (`idModoCierreDeCaja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_cierredecaja_modocierredecaja1_idx` ON `seaandbeach`.`cierredecaja` (`idModoCierreDeCaja` ASC);


-- -----------------------------------------------------
-- Table `seaandbeach`.`factura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `seaandbeach`.`factura` ;

CREATE TABLE IF NOT EXISTS `seaandbeach`.`factura` (
  `idFactura` INT(11) NOT NULL AUTO_INCREMENT,
  `NumFactura` VARCHAR(45) NOT NULL,
  `EstadoFactura` TINYINT(1) NOT NULL,
  `fecha` DATE NULL DEFAULT NULL,
  `Apartamento` INT(11) NOT NULL,
  `cajero` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idFactura`),
  CONSTRAINT `fk_Factura_Apartamento1`
    FOREIGN KEY (`Apartamento`)
    REFERENCES `seaandbeach`.`apartamento` (`Apartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `idCabeceraPedido_UNIQUE` ON `seaandbeach`.`factura` (`idFactura` ASC);

CREATE INDEX `fk_Factura_Apartamento1_idx` ON `seaandbeach`.`factura` (`Apartamento` ASC);


-- -----------------------------------------------------
-- Table `seaandbeach`.`detallecierredecaja`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `seaandbeach`.`detallecierredecaja` ;

CREATE TABLE IF NOT EXISTS `seaandbeach`.`detallecierredecaja` (
  `idFactura` INT(12) NOT NULL,
  `idCierreDeCaja` INT(12) UNSIGNED NOT NULL,
  CONSTRAINT `fk_detallecierredecaja_cierredecaja1`
    FOREIGN KEY (`idCierreDeCaja`)
    REFERENCES `seaandbeach`.`cierredecaja` (`idCierreDeCaja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detallecierredecaja_factura1`
    FOREIGN KEY (`idFactura`)
    REFERENCES `seaandbeach`.`factura` (`idFactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_detallecierredecaja_cierredecaja1_idx` ON `seaandbeach`.`detallecierredecaja` (`idCierreDeCaja` ASC);

CREATE INDEX `fk_detallecierredecaja_factura1_idx` ON `seaandbeach`.`detallecierredecaja` (`idFactura` ASC);


-- -----------------------------------------------------
-- Table `seaandbeach`.`rolempleado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `seaandbeach`.`rolempleado` ;

CREATE TABLE IF NOT EXISTS `seaandbeach`.`rolempleado` (
  `CodigoRol` INT(11) NOT NULL AUTO_INCREMENT,
  `DescripcionRol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CodigoRol`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `idRolEmpleado_UNIQUE` ON `seaandbeach`.`rolempleado` (`CodigoRol` ASC);


-- -----------------------------------------------------
-- Table `seaandbeach`.`empleado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `seaandbeach`.`empleado` ;

CREATE TABLE IF NOT EXISTS `seaandbeach`.`empleado` (
  `Cedula` INT(11) NOT NULL,
  `RUT` VARCHAR(45) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `Telefono` VARCHAR(45) NULL DEFAULT NULL,
  `Direccion` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(16) NOT NULL,
  `CodigoRol` INT(11) NOT NULL,
  PRIMARY KEY (`Cedula`),
  CONSTRAINT `fk_Empleado_RolEmpleado`
    FOREIGN KEY (`CodigoRol`)
    REFERENCES `seaandbeach`.`rolempleado` (`CodigoRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `Cedula_UNIQUE` ON `seaandbeach`.`empleado` (`Cedula` ASC);

CREATE INDEX `fk_Empleado_RolEmpleado_idx` ON `seaandbeach`.`empleado` (`CodigoRol` ASC);


-- -----------------------------------------------------
-- Table `seaandbeach`.`orden`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `seaandbeach`.`orden` ;

CREATE TABLE IF NOT EXISTS `seaandbeach`.`orden` (
  `idOrden` INT(11) NOT NULL AUTO_INCREMENT,
  `Fecha` DATE NOT NULL,
  `Empleado_Cedula_Mesero` INT(11) NOT NULL,
  `Empleado_Cedula_Cajero` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idOrden`),
  CONSTRAINT `fk_Orden_Empleado1`
    FOREIGN KEY (`Empleado_Cedula_Mesero`)
    REFERENCES `seaandbeach`.`empleado` (`Cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `idOrden_UNIQUE` ON `seaandbeach`.`orden` (`idOrden` ASC);

CREATE INDEX `fk_Orden_Empleado1_idx` ON `seaandbeach`.`orden` (`Empleado_Cedula_Mesero` ASC);


-- -----------------------------------------------------
-- Table `seaandbeach`.`detallefactura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `seaandbeach`.`detallefactura` ;

CREATE TABLE IF NOT EXISTS `seaandbeach`.`detallefactura` (
  `idDetalleFactura` INT(11) NOT NULL AUTO_INCREMENT,
  `NumFactura` VARCHAR(45) NOT NULL,
  `idOrden` INT(11) NOT NULL,
  `idFactura` INT(11) NOT NULL,
  PRIMARY KEY (`idDetalleFactura`),
  CONSTRAINT `fk_DetalleFactura_Factura1`
    FOREIGN KEY (`idFactura`)
    REFERENCES `seaandbeach`.`factura` (`idFactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DetalleFactura_Orden1`
    FOREIGN KEY (`idOrden`)
    REFERENCES `seaandbeach`.`orden` (`idOrden`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `idDetalleFactura_UNIQUE` ON `seaandbeach`.`detallefactura` (`idDetalleFactura` ASC);

CREATE INDEX `fk_DetalleFactura_Orden1_idx` ON `seaandbeach`.`detallefactura` (`idOrden` ASC);

CREATE INDEX `fk_DetalleFactura_Factura1_idx` ON `seaandbeach`.`detallefactura` (`idFactura` ASC);


-- -----------------------------------------------------
-- Table `seaandbeach`.`formadepago`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `seaandbeach`.`formadepago` ;

CREATE TABLE IF NOT EXISTS `seaandbeach`.`formadepago` (
  `idFormaDePago` INT(11) NOT NULL AUTO_INCREMENT,
  `TipoPago` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idFormaDePago`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `idFormaDePago_UNIQUE` ON `seaandbeach`.`formadepago` (`idFormaDePago` ASC);


-- -----------------------------------------------------
-- Table `seaandbeach`.`tipoingrediente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `seaandbeach`.`tipoingrediente` ;

CREATE TABLE IF NOT EXISTS `seaandbeach`.`tipoingrediente` (
  `idTipoIngrediente` INT(11) NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipoIngrediente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `idTipoIngrediente_UNIQUE` ON `seaandbeach`.`tipoingrediente` (`idTipoIngrediente` ASC);


-- -----------------------------------------------------
-- Table `seaandbeach`.`ingrediente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `seaandbeach`.`ingrediente` ;

CREATE TABLE IF NOT EXISTS `seaandbeach`.`ingrediente` (
  `idIngrediente` INT(11) NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `idTipoIngrediente` INT(11) NOT NULL,
  PRIMARY KEY (`idIngrediente`),
  CONSTRAINT `fk_Ingrediente_TipoIngrediente1`
    FOREIGN KEY (`idTipoIngrediente`)
    REFERENCES `seaandbeach`.`tipoingrediente` (`idTipoIngrediente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `idIngrediente_UNIQUE` ON `seaandbeach`.`ingrediente` (`idIngrediente` ASC);

CREATE INDEX `fk_Ingrediente_TipoIngrediente1_idx` ON `seaandbeach`.`ingrediente` (`idTipoIngrediente` ASC);


-- -----------------------------------------------------
-- Table `seaandbeach`.`menuitem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `seaandbeach`.`menuitem` ;

CREATE TABLE IF NOT EXISTS `seaandbeach`.`menuitem` (
  `idMenuItem` INT(11) NOT NULL AUTO_INCREMENT,
  `NombrePlato` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(100) NULL DEFAULT NULL,
  `Precio` FLOAT NOT NULL,
  `Estado` TINYINT(1) NOT NULL,
  `idCategoriaItem` INT(11) NOT NULL,
  PRIMARY KEY (`idMenuItem`),
  CONSTRAINT `fk_MenuItem_CategoriaItem1`
    FOREIGN KEY (`idCategoriaItem`)
    REFERENCES `seaandbeach`.`categoriaitem` (`idCategoriaItem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 135
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `idMenuItem_UNIQUE` ON `seaandbeach`.`menuitem` (`idMenuItem` ASC);

CREATE INDEX `fk_MenuItem_CategoriaItem1_idx` ON `seaandbeach`.`menuitem` (`idCategoriaItem` ASC);


-- -----------------------------------------------------
-- Table `seaandbeach`.`ingredientemenuitem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `seaandbeach`.`ingredientemenuitem` ;

CREATE TABLE IF NOT EXISTS `seaandbeach`.`ingredientemenuitem` (
  `Cantidad` INT(11) NULL DEFAULT NULL,
  `idIngrediente` INT(11) NOT NULL,
  `idMenuItem` INT(11) NOT NULL,
  CONSTRAINT `fk_IngredienteMenuItem_Ingrediente1`
    FOREIGN KEY (`idIngrediente`)
    REFERENCES `seaandbeach`.`ingrediente` (`idIngrediente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_IngredienteMenuItem_MenuItem1`
    FOREIGN KEY (`idMenuItem`)
    REFERENCES `seaandbeach`.`menuitem` (`idMenuItem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_IngredienteMenuItem_Ingrediente1_idx` ON `seaandbeach`.`ingredientemenuitem` (`idIngrediente` ASC);

CREATE INDEX `fk_IngredienteMenuItem_MenuItem1_idx` ON `seaandbeach`.`ingredientemenuitem` (`idMenuItem` ASC);


-- -----------------------------------------------------
-- Table `seaandbeach`.`inventario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `seaandbeach`.`inventario` ;

CREATE TABLE IF NOT EXISTS `seaandbeach`.`inventario` (
  `idProducto` INT(11) NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(50) NOT NULL,
  `Cantidad` INT(11) NOT NULL,
  `Precio` INT(11) NOT NULL,
  PRIMARY KEY (`idProducto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `seaandbeach`.`mesa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `seaandbeach`.`mesa` ;

CREATE TABLE IF NOT EXISTS `seaandbeach`.`mesa` (
  `idMesa` INT(11) NOT NULL AUTO_INCREMENT,
  `DetalleMesa` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMesa`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `idMesa_UNIQUE` ON `seaandbeach`.`mesa` (`idMesa` ASC);


-- -----------------------------------------------------
-- Table `seaandbeach`.`modoconsumo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `seaandbeach`.`modoconsumo` ;

CREATE TABLE IF NOT EXISTS `seaandbeach`.`modoconsumo` (
  `idModoConsumo` INT(11) NOT NULL AUTO_INCREMENT,
  `TipoConsumo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idModoConsumo`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `idModoConsumo_UNIQUE` ON `seaandbeach`.`modoconsumo` (`idModoConsumo` ASC);


-- -----------------------------------------------------
-- Table `seaandbeach`.`ofertaitem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `seaandbeach`.`ofertaitem` ;

CREATE TABLE IF NOT EXISTS `seaandbeach`.`ofertaitem` (
  `idOfertaItem` INT(11) NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(45) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Descuento` FLOAT NOT NULL,
  `Fecha` DATE NULL DEFAULT NULL,
  `idMenuItem` INT(11) NOT NULL,
  PRIMARY KEY (`idOfertaItem`),
  CONSTRAINT `fk_OfertaItem_MenuItem2`
    FOREIGN KEY (`idMenuItem`)
    REFERENCES `seaandbeach`.`menuitem` (`idMenuItem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `idOfertaItem_UNIQUE` ON `seaandbeach`.`ofertaitem` (`idOfertaItem` ASC);

CREATE INDEX `fk_OfertaItem_MenuItem2_idx` ON `seaandbeach`.`ofertaitem` (`idMenuItem` ASC);


-- -----------------------------------------------------
-- Table `seaandbeach`.`ordenmenuitem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `seaandbeach`.`ordenmenuitem` ;

CREATE TABLE IF NOT EXISTS `seaandbeach`.`ordenmenuitem` (
  `Cantidad` INT(11) NULL DEFAULT NULL,
  `Comentario` VARCHAR(45) NULL DEFAULT NULL,
  `idMenuItem` INT(11) NOT NULL,
  `idOrden` INT(11) NOT NULL,
  CONSTRAINT `fk_OrdenMenuItem_MenuItem1`
    FOREIGN KEY (`idMenuItem`)
    REFERENCES `seaandbeach`.`menuitem` (`idMenuItem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OrdenMenuItem_Orden1`
    FOREIGN KEY (`idOrden`)
    REFERENCES `seaandbeach`.`orden` (`idOrden`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_OrdenMenuItem_MenuItem1_idx` ON `seaandbeach`.`ordenmenuitem` (`idMenuItem` ASC);

CREATE INDEX `fk_OrdenMenuItem_Orden1_idx` ON `seaandbeach`.`ordenmenuitem` (`idOrden` ASC);


-- -----------------------------------------------------
-- Table `seaandbeach`.`reservacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `seaandbeach`.`reservacion` ;

CREATE TABLE IF NOT EXISTS `seaandbeach`.`reservacion` (
  `Comanda` INT(11) NULL DEFAULT NULL,
  `Fecha` DATE NULL DEFAULT NULL,
  `Habitacion` INT(11) NOT NULL,
  `EstadoDeuda` VARCHAR(45) NOT NULL,
  `idMesa` INT(11) NOT NULL,
  `Apartamento` INT(11) NOT NULL,
  `idModoConsumo` INT(11) NOT NULL,
  `idOrden` INT(11) NOT NULL,
  CONSTRAINT `fk_Reservacion_Apartamento1`
    FOREIGN KEY (`Apartamento`)
    REFERENCES `seaandbeach`.`apartamento` (`Apartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reservacion_Mesa1`
    FOREIGN KEY (`idMesa`)
    REFERENCES `seaandbeach`.`mesa` (`idMesa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reservacion_ModoConsumo1`
    FOREIGN KEY (`idModoConsumo`)
    REFERENCES `seaandbeach`.`modoconsumo` (`idModoConsumo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservacion_orden1`
    FOREIGN KEY (`idOrden`)
    REFERENCES `seaandbeach`.`orden` (`idOrden`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_Reservacion_Mesa1_idx` ON `seaandbeach`.`reservacion` (`idMesa` ASC);

CREATE INDEX `fk_Reservacion_Apartamento1_idx` ON `seaandbeach`.`reservacion` (`Apartamento` ASC);

CREATE INDEX `fk_Reservacion_ModoConsumo1_idx` ON `seaandbeach`.`reservacion` (`idModoConsumo` ASC);

CREATE INDEX `fk_reservacion_orden1_idx` ON `seaandbeach`.`reservacion` (`idOrden` ASC);


-- -----------------------------------------------------
-- Table `seaandbeach`.`valoresdefactura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `seaandbeach`.`valoresdefactura` ;

CREATE TABLE IF NOT EXISTS `seaandbeach`.`valoresdefactura` (
  `idValoresDeFactura` INT(11) NOT NULL AUTO_INCREMENT,
  `NumFactura` VARCHAR(45) NULL DEFAULT NULL,
  `IVA` FLOAT NULL DEFAULT NULL,
  `Propina` INT(11) NULL DEFAULT NULL,
  `TotalFactura` FLOAT NULL DEFAULT NULL,
  `TotalAPagar` FLOAT NULL DEFAULT NULL,
  `idFactura` INT(11) NOT NULL,
  `idFormaDePago` INT(11) NOT NULL,
  PRIMARY KEY (`idValoresDeFactura`),
  CONSTRAINT `fk_FacturaDeValores_Factura1`
    FOREIGN KEY (`idFactura`)
    REFERENCES `seaandbeach`.`factura` (`idFactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_valoresdefactura_formadepago1`
    FOREIGN KEY (`idFormaDePago`)
    REFERENCES `seaandbeach`.`formadepago` (`idFormaDePago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 52
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_FacturaDeValores_Factura1_idx` ON `seaandbeach`.`valoresdefactura` (`idFactura` ASC);

CREATE INDEX `fk_valoresdefactura_formadepago1_idx` ON `seaandbeach`.`valoresdefactura` (`idFormaDePago` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
